name: Build and Package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:21-jdk
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: target/*.jar
